### ISSUE TITLE
Display the name of the person to which the TODO is assigned

### ISSUE THREAD

**Issue by first-developer** [jonathandelgado/SublimeTodoReview#115]
Hi,
Great plugin dude! +1 
It will will be great to add another functionality to your plugin. It will great to display the name of the person to which the TODO is assigned. 
An example : 
```
#From any source file
TODO(first-developer): Blah Blah Blah
```

On the the review result page, I should get this : 
```
# TODO (1)
1. source_file:X              [first-developer] Blah Blah Blah
```

1. I don't think it will to difficult to do this. I look at your code source and I'm wondering if the part of the code must change to achieve the result : 
https://github.com/jonathandelgado/SublimeTodoReview/blob/master/TodoReview.py#L107-L109

2. Or you I make use of the pattern settings for that? 

If you agree with the number [1.] I will make a PR to add this ;)

Thanks a lot

**Comment by jonathandelgado** [comment]
Any reason why assigning tasks would be on inline code and not done through something like github issues?

I more think of this tool as a temporary note finder before committing. 

Not saying no, just trying to understand the use-case. I try to keep this project lean, since one more regex match on a 5k file project is another twenty seconds of searching.

**Comment by first-developer** [comment]
Hi,
You're right, Github issues works well for that :). My bad!
Thanks
