### ISSUE TITLE
Can't view files if folder name contain colon

### ISSUE THREAD

**Issue by onepixelsolid** [jonathandelgado/SublimeTodoReview#119]
I'm working on a Meteor project whereby the folder names contain `:` (colons). Example structure below: 

    project/
        component:name-1/
            foo_bar.coffee
        component:name-2/
            foo_bar.coffee

The package is finding `TODO:` items and showing the correct result list, however when I press `Enter` to view the file, it's opening a black tab with the title of the folder up to the `:` character. Using the example above it would open a blank tab named `component`.

I had a brief look at the package source however I'm not very comfortable with Python :(

I'm guessing a fix would involve just escaping `:` characters in the file path?

**Comment by jonathandelgado** [comment]
The problem is when the file is passed back to SublimeText to open, it natively thinks the colon is a line number, for example `somefile.js:5` would open the file on line 5. This only happens when you are using the `sublime.ENCODED_POSITION` API, which explains why you are not having this issue when opening these files normally.

I don't see a way to fix this with the sublime API the way it is currently.

**Comment by jonathandelgado** [comment]
Going to close this since it is impossible to solve with the way ST3 is currently.
