### ISSUE TITLE
Question. Exclude all folders except

### ISSUE THREAD

**Issue by toastman** [jonathandelgado/SublimeTodoReview#130]
Is it possible to include, for example, only 2 folders and exclude all others ? And if yes - how to achieve this ?

**Comment by jonathandelgado** [comment]
Use the `paths` argument, more information in the readme.

**Comment by UberGruber** [comment]
Sorry for asking in a closed issue, but I'm exactly looking for this. Maybe I'm missing something obvious, but is it possible to use `paths` in the project file setting? If yes how? How can I give a custom command? Only via user key binings? Sorry I'm quite a novice with ST.

The `include_paths` setting is handy but can be tedious to define several folders with absolute paths, even more if you have to update it when creating new folders to check. Is there any other option?

**Comment by jonathandelgado** [comment]
@UberGruber You can define an `include_paths` setting for each of your projects - if that is your problem, more about that in the readme.

There isn't a glob setting for paths, if that is what you are asking. To be honest, sublime is dying. I use Atom now a'days, but I would happily accept a PR if you want to implement that.

**Comment by UberGruber** [comment]
@jonathandelgado Thanks for answering, I asked because I'm a bit confused from your [Arguments](https://github.com/jonathandelgado/SublimeTodoReview#arguments) doc section: where can I specify a `paths` argument? If I'm getting it right it's available for Keybinds only right? If that's so, how can I make a specific Keybind per project or override a general User defined on a project base?

I'd be glad to help but I don't know much of python (to not say nothing). By the look of it, it could be placed  a sort of check for either `include_path` or `exclude_path` setting and go on with wich is present, but I think it's needed a bit of refactoring in the logic of the script too then.  

Atom looks really promising, but I'm not sold yet, I feel it a bit shaky atm but will get better indeed!

**Comment by jonathandelgado** [comment]
@UberGruber Yeah, it would be a large rewrite, since the system currently uses the provided paths for mapping directories. Sublime has a really funky way of expressing folders, in which you can essentially exclude a folder by including it; that is that main reason I wrote it the way I did.

You can specify keymaps by doing something like: https://github.com/jonathandelgado/SublimeTodoReview/blob/master/Default.sublime-keymap, but it won't be per-project. You can, however, specify a `include_path` per project in your `.sublime-project`, more info on that here https://github.com/jonathandelgado/SublimeTodoReview#config

**Comment by UberGruber** [comment]
@jonathandelgado That's what i thought, anyway my case is a sort of _edge case_ since I'm working on other people stuff and didn't want to fluff with their own @todo and other annotations, so including only the paths I'm working on was more sensed. Then again I think that in these cases, the best thing to do is just create a custom tag and stick with it without caring for folder filters. 
Thanks a lot for your time anyway!

**Comment by adisos** [comment]
@jonathandelgado 

Hey, sorry, it's off topic, but I also think about migrating to Atom. Only thing is holding me is https://github.com/facelessuser/BracketHighlighter this package. Do you know is there any plugin like this in Atom?

**Comment by jonathandelgado** [comment]
@adisos You can just search their package manager, https://atom.io/packages/bracket-matcher

I think it's installed by default, by the way.
