### ISSUE TITLE
Re: Crash when calling TodoReview while it's tab is already open (#131)

### ISSUE THREAD

**Issue by Code-Curious** [jonathandelgado/SublimeTodoReview#135]
Unfortunately,  v3.0.7 has not fixed issue #131 . I still get the huge freeze when running TodoReview while its tab is still open, Sublime and my whole computer freezes for a minute.

**Comment by jonathandelgado** [comment]
Yeah, to be frank on this, I really don't know what could be causing this. I know there is a glitch on async in ST2 that may cause something like this, but you mentioned you were on ST3 in the other issue. I just assumed what other people described in #131 was related to your problem.

As I mentioned in the last upgrade message, Sublime has a lot of stupid glitches like this, they aren't because of this plugin, but rather how sublime wraps python. I don't have time to screw around with Sublime, but if you can come up with a solution, I will accept a PR.
