### ISSUE TITLE
When used on a folder in a sidebar, don't list parent folders

### ISSUE THREAD

**Issue by FichteFoll** [jonathandelgado/SublimeTodoReview#137]
When I'm using this on a folder in the sidebar, I am very much interested in having all file paths relative from that directory - especially if it's only one directory and not multiple. If there are multiple, don't go higher than the name of the "scan root directory".

After countless months of idling in a tab, this package has finally managed to find its way into my configuration and I'm very much interested in keeping it alive - if I can manage to enough time for it, that is. Pull requests possible.

**Comment by jonathandelgado** [comment]
I thought this was already a feature - I'll test this soon. Off the top of my head, might be an issue with `paths` not being set properly.

I've added you as a collaborator in the mean time, I trust your judgement if you have anything to add!

**Comment by FichteFoll** [comment]
I determined this to only be the case when `render_include_folder` is set to `true`. Since I made this false, it hasn't occured to me.

**Comment by jonathandelgado** [comment]
@FichteFoll Very interesting, thanks for adding that! I'll make sure I take a look at this soon, it's been a little crazy lately!

**Comment by jonathandelgado** [comment]
Looked into this today, it looks like the `render_folder_depth` will always determine the amount of folders are displayed in the render, the issue you noticed with `render_include_folder` is simply causing   `render_folder_depth` to be set to `0`.

The solution to this would be calculating the depth of each file from the `paths` and then calculating the max between that depth and `render_include_folder`. This is actually a little difficult since we need to determine the actual `paths` that was used for each result within the `draw_file`; so this might actually require a rewrite of the engine to include the `paths` used for each item.

With that being said, this isn't something i'm willing to take on, but I will absolutely accept a PR.

**Comment by FichteFoll** [comment]
Closed through #166.
