### ISSUE TITLE
Crash on OSX w/ No files open

### ISSUE THREAD

**Issue by Nooshu** [jonathandelgado/SublimeTodoReview#76]
Hello,
I seem to be having a problem with the package at the moment. I'm starting a project scan, it starts scanning but crashes ST3 (build 3065) every time it gets to around 13,300 files scanned. This is repeatable and happens every time.

Is there anywhere I can look for a log file to see why the crash is happening? Maybe it is a conflict with another package? I'm happy to post the log file to help get to the bottom of it.

Thanks.

**Comment by jonathandelgado** [comment]
Can't believe it's been a year since this issue was created. Was just reviewing this prior to pushing a new version.

My idea here was to throw a message if we were able to detect a crash was about to happen, which is the most we can do. I implemented this today and realized that querying the actual open tabs causes the crash as well, so trying to detect a crash causes a crash.

End of the day, sublime is dying, stuff like this will never be fixed, so there is nothing that can be done.

**Comment by wbyoung** [comment]
It's been a while since I looked at this either, but just a thought after re-reading the conversation — what if you create the new file/tab before any threaded work and then updated the contents after the work completes?

I think this means the window would appear (and perhaps should have some loading message) immediately rather than once complete. But that could actually be nice.

**Comment by jonathandelgado** [comment]
That would work, but it would remove the functionality of having a single TodoReview tab.

Right now, when you use the command, it will do the following:

- Gets a list of all files
- If `OpenFiles`, gets a list of all (Causes a crash)
- Search
- Searches for existing TodoReview tabs to combine (Causes a crash)
- Renders

If we were to move the render to before the search, it would still cause a crash by searching for  existing TodoReview tabs, since we want to combine them rather than make a new tab every time it is run.

Essentially, we need to look at tabs before both searching and rendering.

**Comment by wbyoung** [comment]
Ah, I see. Too bad.

Thanks for the update and trying to fix it!

**Comment by jonathandelgado** [comment]
Yeah, sad to see sublime is such a state of disarray. Thanks for your time!
