### ISSUE TITLE
Feature: Write output to a project file

### ISSUE THREAD

**Issue by nesler** [jonathandelgado/SublimeTodoReview#97]
Hi,

Would it be possible to add an option to write the todo to an actual file, rather than just opening a tab?
Or is this already possible using the provided command?

I'd like to use it the following way:
When saving/loading a file, trigger the command to update the local todo-list. This way, the todos can be visualized when pushing sources to VCS.

I realize, that this will mean losing the navigation stuff, but that's minor to me :)

**Comment by jonathandelgado** [comment]
I'd accept a PR for that.

**Comment by nesler** [comment]
Allright, I don't have any experience with Sublime Text plugins, but I do know a little Python, so if I get some time, I might look into it myself.

**Comment by jonathandelgado** [comment]
You can also just save the buffer as a file, if you hadn't thought about that. IE, `ctrl + s` on the TodoReview tab.

**Comment by nesler** [comment]
I had, but if I then wanted to update that file, I would have to re-save-as after the changes, no? I haven't tried this, it's just what I expect.

**Comment by jonathandelgado** [comment]
I think the best way to do this is for you to create a private package that waits for a file save, runs TodoReview, then saves the output to wherever you would like. That would be far more efficient that anything we would integrate.

I don't really want to include and onsave functions or other edge case stuff mucking up the package. The save thing is a cool feature, but the additional functions you would need in order to get this to work solely in TodoReview is a bit much.

**Comment by nesler** [comment]
Oh, I wasn't thinking the "on-save" feature should be built into the package. I was more thinking of it like a setting, that would persist the list, rather than just display it in a new tab. Then, I (and other users) could have SublimeText run that command in special scenarios. A lot more flexible, and a lot less cluttering of the package.

I'll still try and take a look at a possible solution an create a PR, then you can take a look and decide if it's something you would like to integrate.

**Comment by jonathandelgado** [comment]
@nesler Right on!
